name: supabase-backup
on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # Runs every day at midnight (corrigido o cron)
env:
  BACKUP_ENABLED: true
jobs:
  run_db_backup:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      SUPABASE_DB_URL: ${{ secrets.SUPABASE_DB_URL }}
      BACKUP_ENABLED: ${{ vars.BACKUP_ENABLED }} # Repository variable (true or false)
    steps:
      - name: Check if backups are enabled
        run: |
          if [ "$BACKUP_ENABLED" != "true" ]; then
            echo "Backups are disabled. Exiting workflow."
            exit 0
          fi
      
      - name: Checkout repository
        if: env.BACKUP_ENABLED == 'true'
        uses: actions/checkout@v4
      
      # Instalar PostgreSQL 17 client tools diretamente
      - name: Install PostgreSQL 17 client
        if: env.BACKUP_ENABLED == 'true'
        run: |
          sudo apt-get update
          sudo apt-get install -y wget ca-certificates
          wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
          echo "deb http://apt.postgresql.org/pub/repos/apt/ $(lsb_release -cs)-pgdg main" | sudo tee /etc/apt/sources.list.d/pgdg.list
          sudo apt-get update
          sudo apt-get install -y postgresql-client-17
      
      - name: Create timestamp folder
        if: env.BACKUP_ENABLED == 'true'
        run: mkdir -p prisma/backups
      
      - name: Backup roles
        if: env.BACKUP_ENABLED == 'true'
        run: |
          /usr/lib/postgresql/17/bin/pg_dumpall --roles-only \
            --dbname="$SUPABASE_DB_URL" \
            --file=prisma/backups/roles.sql
      
      - name: Backup schema
        if: env.BACKUP_ENABLED == 'true'
        run: |
          /usr/lib/postgresql/17/bin/pg_dump \
            --dbname="$SUPABASE_DB_URL" \
            --schema-only \
            --file=prisma/backups/schema.sql
      
      - name: Backup data
        if: env.BACKUP_ENABLED == 'true'
        run: |
          /usr/lib/postgresql/17/bin/pg_dump \
            --dbname="$SUPABASE_DB_URL" \
            --data-only \
            --file=prisma/backups/data.sql
      
      - name: Commit backups
        if: env.BACKUP_ENABLED == 'true'
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Supabase backup - $(date +'%Y-%m-%d %H:%M:%S')"
